manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 3062245d5980f5c89a81cff28a7389e55396d82a
      import:
        name-allowlist:
          - cmsis_6
          - hal_stm32
          - hal_st
