manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 04d263dc5419e12604feae0c051286f697acb2bd
      import:
        name-allowlist:
          - cmsis_6
          - hal_stm32
          - hal_st
